# Generated by Django 2.2.2 on 2019-07-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20190701_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Close'), (1, 'Open')]),
        ),
    ]
