# Generated by Django 2.2.2 on 2019-07-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20190701_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
