# Generated by Django 2.2.2 on 2019-07-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
