# Generated by Django 2.2.2 on 2019-07-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20190702_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='content_fast',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
