# Generated by Django 2.2.2 on 2019-07-02 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_new_content_fast'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Người vô danh', max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.New')),
            ],
        ),
    ]
