# Generated by Django 2.2.2 on 2019-07-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
