# Generated by Django 2.2.2 on 2019-07-02 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='new_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='client.New'),
        ),
    ]
