# Generated by Django 2.2.3 on 2019-07-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='path_name',
            field=models.CharField(max_length=365, null=True),
        ),
    ]
